# Generated by Django 3.2.8 on 2021-10-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='quantity',
            new_name='discount',
        ),
    ]
