# Generated by Django 3.2.8 on 2021-10-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_quantity_course_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='time',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
