# Generated by Django 3.2.8 on 2021-10-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('OnShipping', 'OnShipping'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=15),
        ),
        migrations.AlterField(
            model_name='ordercourse',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
