# Generated by Django 3.2.8 on 2021-10-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211016_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercourse',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='New', max_length=15),
        ),
    ]
