# Generated by Django 3.2.8 on 2021-10-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ordercourse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercourse',
            name='status',
        ),
    ]
